apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: free-space-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
spec:
  defaultBackend:
    service:
      name: frontend-free-space-service
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: m-content-service
            port:
              number: 80