apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-free-space-deployment
  labels:
    app: frontend-free-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-free-space
  template:
    metadata:
      labels:
        app: frontend-free-space
    spec:
      containers:
      - name: frontend-free-space
        image: carloosbaquero/frontend-free-space:v6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-free-space-service
  labels:
    app:  frontend-free-space
spec:
  selector:
    app: frontend-free-space
  type: NodePort  
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30000

