apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-free-space-configmap
data:
  VITE_M_USERS_HOST: localhost 
  VITE_M_USERS_PORT: "3002"
  VITE_M_CONTENT_HOST: localhost
  VITE_M_CONTENT_PORT: "3001"
